### ISSUE TITLE
Missed (at least one) gem on GitLab

### ISSUE THREAD

**Issue by ylluminate** [jruby/jruby-lint#14]
Just wanted to make a note that when running this on GitLab 7.0rc1 source, it missed the `charlock_holmes` gem as being a native c based gem: 
https://gist.github.com/1fd6ddde34711022c7cb

**Comment by enebo** [comment]
@ylluminate yeah this gem does not seem to have a section of known not to work gems in it.  I did notice in the case of charlock_holmes there is a charlock_holmes-jruby.  So I added it to cext suggestion list.
