### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by sils** [jruby/jruby-lint#16]
Hi, there was no commit since 2013, is this still maintained? The main JRuby repo seems to be active and you have a roadmap for this repo.

We're working on coala (coala-analyzer.org) and are possibly interested in integrating jruby-lint to our collection of supported linters, possibly migrating your algorithms to use coala could ease getting your roadmap done as coala already supports things like auto fixing stuff for the useror JSON output, editor plugins and whatnot and you as a developer of the actual analysis shouldn't need to care.

**Comment by enebo** [comment]
A new version will be out soon but yeah it had been abandoned for a while
