### ISSUE TITLE
OptArgNode.java - accept: java.lang.UnsupportedOperationException: Not supported yet.

### ISSUE THREAD

**Issue by kowal** [jruby/jruby-lint#8]
On jruby 1.7.0.RC1 (1.9.3p203), I'm trying to check simple Sinatra application.

I'm getting:

``` bash
OptArgNode.java:71:in `accept': java.lang.UnsupportedOperationException: Not supported yet.
    from null:-1:in `invoke'
    from null:-1:in `invoke'
    from null:-1:in `invoke'
    from JavaMethod.java:455:in `invokeDirectWithExceptionHandling'
        ...
```

Full stack trace: https://gist.github.com/3878211

Is this jruby-lint or maybe jruby issue?

**Comment by enebo** [comment]
This I believe was an issue in an old JRuby where optargnode had no visitor defined.
